[general]
import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 96, lines = 26 }
opacity = 0.9
padding = { x = 8, y = 8 }

[font]
normal = { family = "FiraCode Nerd Font",  style = "Regular"}
size = 10

[colors.primary]
foreground = "#ffffff"

[cursor]
style = { shape = "Underline", blinking = "On"}

[mouse]
hide_when_typing = true